import "./globals.css";
import { Inter } from "next/font/google";
import { Navigation } from "@/app/Navigation";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navigation />

        <div className="flex min-h-screen flex-col p-4 gap-4 mr-32 mx-auto container">
          {children}
        </div>
      </body>
    </html>
  );
}
